name: imthon5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_gemini: ^3.0.0
  flutter_riverpod: ^2.6.1
  flutter_sound: ^9.28.0
  flutter_tts: ^4.2.3
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  mockito: ^5.4.6
  speech_to_text: ^7.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
